### ISSUE TITLE
ENV var substitution

### ISSUE THREAD

**Issue by whizzzkid** [buildkite-plugins/artifacts-buildkite-plugin#105]
The following ~~works~~ (edit: it doesn't as expected, it defaults to '0' always) in a [build-matrix](https://buildkite.com/docs/pipelines/configure/workflows/build-matrix):

```yml
- name: 'Some Job'
    branches: '!main'
    depends_on:
      - some_other_job
    matrix:
      setup:
        shard:
          - '1'
          - '2'
          - '3'
          - '4'
    timeout_in_minutes: 15
    command: './run.sh --shard={{matrix.shard}}/4'
    retry:
      automatic: true
    plugins:
      - artifacts#v1.9.4:
          upload: 'some-job-report'
          compressed: some-job-${BUILDKITE_BUILD_NUMBER}-job_{{matrix.shard}}-try_${BUILDKITE_RETRY_COUNT}.zip
```

But this does not work in a pipeline with dynamically defined steps:

```yml
- label: 'Some Job [Shard: 1/4]'
  branches: "!main"
  timeout_in_minutes: 15
  command: './run.sh --shard=1/4'
  depends_on:
    - some_other_job
  retry:
    automatic: true
  plugins:
    - artifacts#v1.9.4:
        upload: some-job-report
        compressed: some-job-${BUILDKITE_BUILD_NUMBER}-shard_1-try_$${BUILDKITE_RETRY_COUNT}.zip
```

The above code is generated as dynamic step for the pipeline so this gets converted as for the step:

```yml
  plugins:
    - artifacts#v1.9.4:
        upload: some-job-report
        compressed: some-job-<BUILD_NUMBER>-shard_1-try_${BUILDKITE_RETRY_COUNT}.zip
```

The env-var never gets replaced and what's left is:
```sh
No files matched paths:  some-job-12345-shard_1-try_${BUILDKITE_RETRY_COUNT}.zip
--
  | ~/builds/ip-10-10-10-10-compute/<build_agent>

```

How can I get env vars to be substituted in the asset path?
