### ISSUE TITLE
Incorrect download path 

### ISSUE THREAD

**Issue by rcoup** [buildkite-plugins/artifacts-buildkite-plugin#24]
I created an artifact via:
```yaml
  - label: 'build things'
    ...
    artifact_paths:
      - "myapp/target/myapp-dev.war"
```
which is logged as:
```
Uploading artifacts | 0s
--|--
  | $ buildkite-agent artifact upload myapp/target/myapp-dev.war
  | 2018-08-28 13:47:40 INFO   Found 1 files that match "myapp/target/myapp-dev.war"
  | 2018-08-28 13:47:40 INFO   Creating (0-1)/1 artifacts
  | 2018-08-28 13:47:41 INFO   Uploading artifact abcd1234-bc46-42e5-88f0-abcdef123456 myapp/target/myapp-dev.war (132637217 bytes)
```

Then I download in another step via:
```yaml
  - label: 'package things'
    command:
      - pwd
      - ls
      - "find . -name *.war"
    plugins:
      artifacts#v1.2.0:
        download: "myapp/target/*.war"
      docker#v1.4.0:
        image: "ubuntu:trusty"
        workdir: /src
```
Which is logged as:
```
Downloading artifacts | 1m 5s
--|--
  | 2018-08-28 13:48:46 INFO   Searching for artifacts: "myapp/target/*.war"
  | 2018-08-28 13:48:47 INFO   Found 1 artifacts. Starting to download to: /var/lib/buildkite-agent/builds/buildkite1-i-abcdef123456-1/acme/myapp
  | 2018-08-28 13:49:51 INFO   Successfully downloaded "myapp/target/myapp-dev.war" 132637217 bytes

Running ... | 1s
--|--
  | + pwd
  | /src
  | + ls
  | /src
  | myapp  target ...
  | + find . -name '*.war'
  | ./target/myapp-dev.war
```

**I'd expect the file to be in `./myapp/target/myapp-dev.war`, but instead it's in `./target/myapp-dev.war`**

The [docs say](https://buildkite.com/docs/agent/v3/cli-artifact#downloading-artifacts):
> Downloading all the files uploaded to `log` (including all subdirectories) into a local `log` directory (note that local directories will be created to match the uploaded file paths):
>
>     buildkite-agent artifact download "log/*" .

1. Am I missing something?
2. What determines if the subdirectories get created?
3. I can't see how you can easily fix it without breaking a pile of existing pipelines. Maybe it can have the docs corrected?
