### ISSUE TITLE
Allow automatic zip/unzip

### ISSUE THREAD

**Issue by jmendiara** [buildkite-plugins/artifacts-buildkite-plugin#30]
It would be great if the plugin zips/unzips artifacts automatically
A build step can generate a lot of artifacts: Test results, htmls, screenshots... 
Currently, the UI does not have a "Download all" button, and don't know if its feasible to implement

Having auto-package/un-package artifacts will allow to download them at one shot and save space on artifacts server

In terms of plugin api, it could be something like
```yml
steps:
  - plugins:
      - artifacts#v1.2.0:
          upload: [ "log/**/*.log", "debug/*.error" ] 
          # makes a `output.tar.gz` with all the files found by the `upload` directive
          # and uploads only an artifact called `output.tar.gz`
          pack: "output.tar.gz"
```

```yml
steps:
  - plugins:
      - artifacts#v1.2.0:
          download: [ "log/**/*.log", "debug/*.error" ]
          # downloads `output.tar.gz` and decompress only
          # the files matching the `download` directive 
          pack: "output.tar.gz"
```
