### ISSUE TITLE
MULTIPLE_UPLOADS unbound variable Bug with post-command hook

### ISSUE THREAD

**Issue by mgkeen** [buildkite-plugins/artifacts-buildkite-plugin#48]
Been getting this error for the last couple of days:

```
/var/lib/buildkite-agent/plugins/github-com-buildkite-plugins-artifacts-buildkite-plugin/hooks/post-command: line 61: MULTIPLE_UPLOADS: unbound variable
```

Nothing has changed in our pipeline. I see there was a commit recently that set a failure on unbound variables here:

https://github.com/buildkite-plugins/artifacts-buildkite-plugin/commit/0165d638798111398456708dd4d8d379859ad315#diff-1ec88eb02937eb86424b55abfa2769f0

This is in a pipeline step that only does an artifact download:

```
- artifacts:
          download: 
            from: "zips/*.zip"
            to: infrastructure/main
```
