### ISSUE TITLE
environment variable not respected in filename/path

### ISSUE THREAD

**Issue by AntAreS24** [buildkite-plugins/artifacts-buildkite-plugin#87]
Hi,

We've been using the plugin for a while now and everything is working fine until yesterday (5th July 2023) where our environment variable(s) defined in the `upload`/`download` path are not respected anymore:
```
steps:
  - wait
  - label: ":mocha: Install test and zip"
    if: build.branch != "master" && build.tag == null
    commands:
      - make install test build zip
    env:
      RELEASE_FOLDER: "latest"
    plugins:
      - artifacts#v1.9.0:
          upload: "$RELEASE_FOLDER-alpha.tar.gz"
```

This result in the following in the logs:
```
2023-07-05 02:22:43 INFO   File not found: $RELEASE_FOLDER-alpha.tar.gz
2023-07-05 02:22:43 INFO   No files matched paths: $RELEASE_FOLDER-alpha.tar.gz
```

I also tried variable interpolation with `$$RELEASE_FOLDER` but same result.
