### ISSUE TITLE
Can whole folders be uploaded compressed?

### ISSUE THREAD

**Issue by twometresteve** [buildkite-plugins/artifacts-buildkite-plugin#88]
I'm trying to upload a whole folder, including a nested hierarchy under it, as a zip file.  I've tried these, but none work:

```
    plugins:
        - artifacts#v1.9.0:
            upload: "my_folder"
            compressed: "my_folder.zip"

    plugins:
        - artifacts#v1.9.0:
            upload: "my_folder/**"
            compressed: "my_folder.zip"

    plugins:
        - artifacts#v1.9.0:
            upload: "my_folder/**/*"
            compressed: "my_folder.zip"
```

Is it possible, please?
