### ISSUE TITLE
ingore-missing doesn't work with compressed

### ISSUE THREAD

**Issue by jameslnewell** [buildkite-plugins/artifacts-buildkite-plugin#89]
Using this config:

```yml
  ignore-missing: true
  upload: coverage/
  compressed: coverage.tgz
```

When `coverage/` doesn't exist I get the following error:

```
Running plugin artifacts post-command hook | 0s
-- | --
  | $ /var/lib/buildkite-agent/plugins/github-com-buildkite-plugins-artifacts-buildkite-plugin-v1-9-0/hooks/post-command
  | ~/builds/buildkite-arm-i-0135a2a4d382b6665-1/mryum/buildkite-components ~/builds/buildkite-arm-i-0135a2a4d382b6665-1/mryum/buildkite-components
  | Compressing coverage/ to coverage.tgz | 0s
  | tar: coverage: Cannot stat: No such file or directory
  | tar: Exiting with failure status due to previous errors
  | ~/builds/buildkite-arm-i-0135a2a4d382b6665-1/mryum/buildkite-components
```

But I expected it to fail silently due to `ignore-missing`??

**Comment by pzeballos** [comment]
Thanks for raising it @jameslnewell! we worked on a fix and we'll do a release during the next days :)

**Comment by jameslnewell** [comment]
I think this still needs to be implemented for the non-`SINGULAR_UPLOAD_OBJECT` code path:

Config:
```yml
    plugins:
      - artifacts#v1.9.3:
          ignore-missing: true
          compressed: coverage.tgz
          upload:
            - test/unit/coverage/
```

Error:
```
Compressing test/unit/coverage/ to coverage.tgz | 0s
 tar: test/unit/coverage: Cannot stat: No such file or directory
 tar: Exiting with failure status due to previous errors
```
