### ISSUE TITLE
`ignore-missing` doesn't work with `compressed` & `download` configuration

### ISSUE THREAD

**Issue by timnolte** [buildkite-plugins/artifacts-buildkite-plugin#99]
If I have a step that can't `upload` then there is no archive to download.

Upload: (_step can soft-fail_)

```yaml
  - label: ":pipeline: Prime Cache"
    key: "prime-cache"
    soft_fail:
      - exit_status: 1
    command:
      - 'echo "--- Creating R Packages Cache..."'
    plugins:
      # Upload package cache to artifacts.
      # See https://github.com/buildkite-plugins/artifacts-buildkite-plugin
      - artifacts:
          ignore-missing: true
          upload: "${R_CACHE_LOCATION}"
          compressed: renv_cache.tgz
```

Download: (_archive may not exist_)

```yaml
      - artifacts:
          step: "prime-cache"
          ignore-missing: true
          download: "${R_CACHE_LOCATION}/**/*"
          compressed: renv_cache.tgz
```

_Originally posted by @timnolte in https://github.com/buildkite-plugins/artifacts-buildkite-plugin/issues/89#issuecomment-2052159837_
